CREATE TABLE TROL
(
  CODROL     VARCHAR2(3 BYTE)                   NOT NULL,
  DESROL     VARCHAR2(50 BYTE),
  CODUSRMOD  VARCHAR2(8 BYTE),
  FLGMODTYP  CHAR(1 BYTE),
  TMSLSTMOD  TIMESTAMP(6)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN TROL.CODROL IS 'Codice univoco del ruolo';

COMMENT ON COLUMN TROL.DESROL IS 'Descrizione del ruolo';

COMMENT ON COLUMN TROL.CODUSRMOD IS 'Codice utente modificatore';

COMMENT ON COLUMN TROL.FLGMODTYP IS 'Tipo di modifica';

COMMENT ON COLUMN TROL.TMSLSTMOD IS 'Data di modifica';


