'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class dbEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=dbEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property TFNC() As DbSet(Of TFNC)
    Public Overridable Property TGRPARE() As DbSet(Of TGRPARE)
    Public Overridable Property TROL() As DbSet(Of TROL)
    Public Overridable Property TROLFNC() As DbSet(Of TROLFNC)
    Public Overridable Property TSYSPAR() As DbSet(Of TSYSPAR)
    Public Overridable Property TUSR() As DbSet(Of TUSR)
    Public Overridable Property TUSRROL() As DbSet(Of TUSRROL)
    Public Overridable Property VMEN() As DbSet(Of VMEN)

End Class
