'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization

<DataContract(IsReference:=True)>
Partial Public Class TSYSPAR
    <DataMember()>
    Public Property CODSYSPAR As String
    <DataMember()>
    Public Property NUMSYSPARIDX As Short
    <DataMember()>
    Public Property DESPARVAL As String
    <DataMember()>
    Public Property DESPARDES As String

End Class
