ALTER TABLE TUSRROL ADD (
  CONSTRAINT RGRPUSR01 
 FOREIGN KEY (CODGRPARE) 
 REFERENCES TGRPARE (CODGRPARE),
  CONSTRAINT RROLUSR01 
 FOREIGN KEY (CODROL) 
 REFERENCES TROL (CODROL),
  CONSTRAINT RUSRUSR01 
 FOREIGN KEY (CODCMPGRP, CODUSR) 
 REFERENCES TUSR (CODCMPGRP,CODUSR));
