'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WcfService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="HeaderInput", [Namespace]:="http://schemas.datacontract.org/2004/07/Service"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WcfService.HeaderOutput)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TUSR)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TUSRROL())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TUSRROL)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TGRPARE)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TROL)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TROLFNC())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TROLFNC)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TFNC)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TUSR())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TROL())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TFNC())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.VMEN())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.VMEN)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TSYSPAR)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WcfService.GetFilteredOfTUSR)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WcfService.GetFilteredOfTROL))>  _
    Partial Public Class HeaderInput
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private securityTokenField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private serviceParamField As Object
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property securityToken() As String
            Get
                Return Me.securityTokenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.securityTokenField, value) <> true) Then
                    Me.securityTokenField = value
                    Me.RaisePropertyChanged("securityToken")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property serviceParam() As Object
            Get
                Return Me.serviceParamField
            End Get
            Set
                If (Object.ReferenceEquals(Me.serviceParamField, value) <> true) Then
                    Me.serviceParamField = value
                    Me.RaisePropertyChanged("serviceParam")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="HeaderOutput", [Namespace]:="http://schemas.datacontract.org/2004/07/Service"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WcfService.HeaderInput)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TUSR)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TUSRROL())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TUSRROL)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TGRPARE)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TROL)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TROLFNC())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TROLFNC)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TFNC)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TUSR())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TROL())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TFNC())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.VMEN())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.VMEN)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Domain.TSYSPAR)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WcfService.GetFilteredOfTUSR)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WcfService.GetFilteredOfTROL))>  _
    Partial Public Class HeaderOutput
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private securityTokenField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private serviceParamField As Object
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property securityToken() As String
            Get
                Return Me.securityTokenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.securityTokenField, value) <> true) Then
                    Me.securityTokenField = value
                    Me.RaisePropertyChanged("securityToken")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property serviceParam() As Object
            Get
                Return Me.serviceParamField
            End Get
            Set
                If (Object.ReferenceEquals(Me.serviceParamField, value) <> true) Then
                    Me.serviceParamField = value
                    Me.RaisePropertyChanged("serviceParam")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetFilteredOfTUSR", [Namespace]:="http://schemas.datacontract.org/2004/07/Service.DataContracts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetFilteredOfTUSR
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ParametersField As Domain.TUSR
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private pageNumberField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private pageSizeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private sortField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private sortDirectionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private totalrowsField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Parameters() As Domain.TUSR
            Get
                Return Me.ParametersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ParametersField, value) <> true) Then
                    Me.ParametersField = value
                    Me.RaisePropertyChanged("Parameters")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property pageNumber() As Integer
            Get
                Return Me.pageNumberField
            End Get
            Set
                If (Me.pageNumberField.Equals(value) <> true) Then
                    Me.pageNumberField = value
                    Me.RaisePropertyChanged("pageNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property pageSize() As Integer
            Get
                Return Me.pageSizeField
            End Get
            Set
                If (Me.pageSizeField.Equals(value) <> true) Then
                    Me.pageSizeField = value
                    Me.RaisePropertyChanged("pageSize")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property sort() As String
            Get
                Return Me.sortField
            End Get
            Set
                If (Object.ReferenceEquals(Me.sortField, value) <> true) Then
                    Me.sortField = value
                    Me.RaisePropertyChanged("sort")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property sortDirection() As String
            Get
                Return Me.sortDirectionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.sortDirectionField, value) <> true) Then
                    Me.sortDirectionField = value
                    Me.RaisePropertyChanged("sortDirection")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property totalrows() As Integer
            Get
                Return Me.totalrowsField
            End Get
            Set
                If (Me.totalrowsField.Equals(value) <> true) Then
                    Me.totalrowsField = value
                    Me.RaisePropertyChanged("totalrows")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetFilteredOfTROL", [Namespace]:="http://schemas.datacontract.org/2004/07/Service.DataContracts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetFilteredOfTROL
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ParametersField As Domain.TROL
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private pageNumberField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private pageSizeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private sortField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private sortDirectionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private totalrowsField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Parameters() As Domain.TROL
            Get
                Return Me.ParametersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ParametersField, value) <> true) Then
                    Me.ParametersField = value
                    Me.RaisePropertyChanged("Parameters")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property pageNumber() As Integer
            Get
                Return Me.pageNumberField
            End Get
            Set
                If (Me.pageNumberField.Equals(value) <> true) Then
                    Me.pageNumberField = value
                    Me.RaisePropertyChanged("pageNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property pageSize() As Integer
            Get
                Return Me.pageSizeField
            End Get
            Set
                If (Me.pageSizeField.Equals(value) <> true) Then
                    Me.pageSizeField = value
                    Me.RaisePropertyChanged("pageSize")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property sort() As String
            Get
                Return Me.sortField
            End Get
            Set
                If (Object.ReferenceEquals(Me.sortField, value) <> true) Then
                    Me.sortField = value
                    Me.RaisePropertyChanged("sort")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property sortDirection() As String
            Get
                Return Me.sortDirectionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.sortDirectionField, value) <> true) Then
                    Me.sortDirectionField = value
                    Me.RaisePropertyChanged("sortDirection")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property totalrows() As Integer
            Get
                Return Me.totalrowsField
            End Get
            Set
                If (Me.totalrowsField.Equals(value) <> true) Then
                    Me.totalrowsField = value
                    Me.RaisePropertyChanged("totalrows")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WcfService.IWcfService")>  _
    Public Interface IWcfService
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TUSR) of message MessageInputOf_TUSR does not match the default value (GetUserRolesByCompanyAndUsername)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/GetUserRolesByCompanyAndUsername", ReplyAction:="http://tempuri.org/IWcfService/GetUserRolesByCompanyAndUsernameResponse")>  _
        Function GetUserRolesByCompanyAndUsername(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_TUSR
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_GetFilteredOf_TUSR) of message MessageInputOf_GetFilteredOf_TUSR does not match the default value (GetFilteredUsers)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/GetFilteredUsers", ReplyAction:="http://tempuri.org/IWcfService/GetFilteredUsersResponse")>  _
        Function GetFilteredUsers(ByVal request As WcfService.MessageInputOf_GetFilteredOf_TUSR) As WcfService.MessageOutputOf_IListOf_TUSR
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TUSR) of message MessageInputOf_TUSR does not match the default value (GetUserByPrimaryKey)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/GetUserByPrimaryKey", ReplyAction:="http://tempuri.org/IWcfService/GetUserByPrimaryKeyResponse")>  _
        Function GetUserByPrimaryKey(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_TUSR
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TUSR) of message MessageInputOf_TUSR does not match the default value (InsertUser)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/InsertUser", ReplyAction:="http://tempuri.org/IWcfService/InsertUserResponse")>  _
        Function InsertUser(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_TUSR
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TUSR) of message MessageInputOf_TUSR does not match the default value (DeleteUser)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/DeleteUser", ReplyAction:="http://tempuri.org/IWcfService/DeleteUserResponse")>  _
        Function DeleteUser(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_TUSR
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TUSR) of message MessageInputOf_TUSR does not match the default value (UpdateUser)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/UpdateUser", ReplyAction:="http://tempuri.org/IWcfService/UpdateUserResponse")>  _
        Function UpdateUser(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_TUSR
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_GetFilteredOf_TROL) of message MessageInputOf_GetFilteredOf_TROL does not match the default value (GetFilteredRoles)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/GetFilteredRoles", ReplyAction:="http://tempuri.org/IWcfService/GetFilteredRolesResponse")>  _
        Function GetFilteredRoles(ByVal request As WcfService.MessageInputOf_GetFilteredOf_TROL) As WcfService.MessageOutputOf_IListOf_TROL
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TROL) of message MessageInputOf_TROL does not match the default value (GetRoleByPrimaryKey)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/GetRoleByPrimaryKey", ReplyAction:="http://tempuri.org/IWcfService/GetRoleByPrimaryKeyResponse")>  _
        Function GetRoleByPrimaryKey(ByVal request As WcfService.MessageInputOf_TROL) As WcfService.MessageOutputOf_TROL
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TROL) of message MessageInputOf_TROL does not match the default value (GetAllRoles)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/GetAllRoles", ReplyAction:="http://tempuri.org/IWcfService/GetAllRolesResponse")>  _
        Function GetAllRoles(ByVal request As WcfService.MessageInputOf_TROL) As WcfService.MessageOutputOf_IListOf_TROL
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TUSR) of message MessageInputOf_TUSR does not match the default value (GetRolesAndAllowedFunctions)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/GetRolesAndAllowedFunctions", ReplyAction:="http://tempuri.org/IWcfService/GetRolesAndAllowedFunctionsResponse")>  _
        Function GetRolesAndAllowedFunctions(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_ListOf_TROL
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TUSR) of message MessageInputOf_TUSR does not match the default value (GetRolesAssociableToUser)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/GetRolesAssociableToUser", ReplyAction:="http://tempuri.org/IWcfService/GetRolesAssociableToUserResponse")>  _
        Function GetRolesAssociableToUser(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_IListOf_TROL
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TUSR) of message MessageInputOf_TUSR does not match the default value (GetRolesAssociatedToUser)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/GetRolesAssociatedToUser", ReplyAction:="http://tempuri.org/IWcfService/GetRolesAssociatedToUserResponse")>  _
        Function GetRolesAssociatedToUser(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_ListOf_TROL
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TROL) of message MessageInputOf_TROL does not match the default value (UpdateRole)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/UpdateRole", ReplyAction:="http://tempuri.org/IWcfService/UpdateRoleResponse")>  _
        Function UpdateRole(ByVal request As WcfService.MessageInputOf_TROL) As WcfService.MessageOutputOf_TROL
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TROL) of message MessageInputOf_TROL does not match the default value (InsertRole)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/InsertRole", ReplyAction:="http://tempuri.org/IWcfService/InsertRoleResponse")>  _
        Function InsertRole(ByVal request As WcfService.MessageInputOf_TROL) As WcfService.MessageOutputOf_TROL
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TROL) of message MessageInputOf_TROL does not match the default value (DeleteRole)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/DeleteRole", ReplyAction:="http://tempuri.org/IWcfService/DeleteRoleResponse")>  _
        Function DeleteRole(ByVal request As WcfService.MessageInputOf_TROL) As WcfService.MessageOutputOf_TROL
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TFNC) of message MessageInputOf_TFNC does not match the default value (getRolesByControllerAction)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/getRolesByControllerAction", ReplyAction:="http://tempuri.org/IWcfService/getRolesByControllerActionResponse")>  _
        Function getRolesByControllerAction(ByVal request As WcfService.MessageInputOf_TFNC) As WcfService.MessageOutputOf_ListOf_TROL
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TROL) of message MessageInputOf_TROL does not match the default value (GetFuncionsWithPermissions)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/GetFuncionsWithPermissions", ReplyAction:="http://tempuri.org/IWcfService/GetFuncionsWithPermissionsResponse")>  _
        Function GetFuncionsWithPermissions(ByVal request As WcfService.MessageInputOf_TROL) As WcfService.MessageOutputOf_ListOf_TFNC
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TROLFNC) of message MessageInputOf_TROLFNC does not match the default value (InsertDeleteAssociationFunctToRole)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/InsertDeleteAssociationFunctToRole", ReplyAction:="http://tempuri.org/IWcfService/InsertDeleteAssociationFunctToRoleResponse")>  _
        Function InsertDeleteAssociationFunctToRole(ByVal request As WcfService.MessageInputOf_TROLFNC) As WcfService.MessageOutputOf_TROLFNC
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_ListOf_TUSRROL) of message MessageInputOf_ListOf_TUSRROL does not match the default value (InsertUserRole)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/InsertUserRole", ReplyAction:="http://tempuri.org/IWcfService/InsertUserRoleResponse")>  _
        Function InsertUserRole(ByVal request As WcfService.MessageInputOf_ListOf_TUSRROL) As WcfService.MessageOutputOf_TUSRROL
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_ListOf_TUSRROL) of message MessageInputOf_ListOf_TUSRROL does not match the default value (DeleteUserRole)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/DeleteUserRole", ReplyAction:="http://tempuri.org/IWcfService/DeleteUserRoleResponse")>  _
        Function DeleteUserRole(ByVal request As WcfService.MessageInputOf_ListOf_TUSRROL) As WcfService.MessageOutputOf_TUSRROL
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TUSR) of message MessageInputOf_TUSR does not match the default value (GetMenuByUser)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/GetMenuByUser", ReplyAction:="http://tempuri.org/IWcfService/GetMenuByUserResponse")>  _
        Function GetMenuByUser(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_ListOf_VMEN
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/CheckDbConnection", ReplyAction:="http://tempuri.org/IWcfService/CheckDbConnectionResponse")>  _
        Function CheckDbConnection() As Boolean
        
        'CODEGEN: Generating message contract since the wrapper name (MessageInputOf_TSYSPAR) of message MessageInputOf_TSYSPAR does not match the default value (GetSysParByPrimaryKey)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWcfService/GetSysParByPrimaryKey", ReplyAction:="http://tempuri.org/IWcfService/GetSysParByPrimaryKeyResponse")>  _
        Function GetSysParByPrimaryKey(ByVal request As WcfService.MessageInputOf_TSYSPAR) As WcfService.MessageOutputOf_TSYSPAR
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageInputOf_TUSR", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageInputOf_TUSR
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadIn As WcfService.HeaderInput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyIn As Domain.TUSR
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TUSR)
            MyBase.New
            Me.HeadIn = HeadIn
            Me.BodyIn = BodyIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageOutputOf_TUSR", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageOutputOf_TUSR
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadOut As WcfService.HeaderOutput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyOut As Domain.TUSR
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadOut As WcfService.HeaderOutput, ByVal BodyOut As Domain.TUSR)
            MyBase.New
            Me.HeadOut = HeadOut
            Me.BodyOut = BodyOut
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageInputOf_GetFilteredOf_TUSR", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageInputOf_GetFilteredOf_TUSR
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadIn As WcfService.HeaderInput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyIn As WcfService.GetFilteredOfTUSR
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As WcfService.GetFilteredOfTUSR)
            MyBase.New
            Me.HeadIn = HeadIn
            Me.BodyIn = BodyIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageOutputOf_IListOf_TUSR", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageOutputOf_IListOf_TUSR
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadOut As WcfService.HeaderOutput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyOut() As Domain.TUSR
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadOut As WcfService.HeaderOutput, ByVal BodyOut() As Domain.TUSR)
            MyBase.New
            Me.HeadOut = HeadOut
            Me.BodyOut = BodyOut
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageInputOf_GetFilteredOf_TROL", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageInputOf_GetFilteredOf_TROL
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadIn As WcfService.HeaderInput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyIn As WcfService.GetFilteredOfTROL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As WcfService.GetFilteredOfTROL)
            MyBase.New
            Me.HeadIn = HeadIn
            Me.BodyIn = BodyIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageOutputOf_IListOf_TROL", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageOutputOf_IListOf_TROL
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadOut As WcfService.HeaderOutput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyOut() As Domain.TROL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadOut As WcfService.HeaderOutput, ByVal BodyOut() As Domain.TROL)
            MyBase.New
            Me.HeadOut = HeadOut
            Me.BodyOut = BodyOut
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageInputOf_TROL", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageInputOf_TROL
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadIn As WcfService.HeaderInput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyIn As Domain.TROL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TROL)
            MyBase.New
            Me.HeadIn = HeadIn
            Me.BodyIn = BodyIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageOutputOf_TROL", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageOutputOf_TROL
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadOut As WcfService.HeaderOutput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyOut As Domain.TROL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadOut As WcfService.HeaderOutput, ByVal BodyOut As Domain.TROL)
            MyBase.New
            Me.HeadOut = HeadOut
            Me.BodyOut = BodyOut
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageOutputOf_ListOf_TROL", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageOutputOf_ListOf_TROL
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadOut As WcfService.HeaderOutput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyOut() As Domain.TROL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadOut As WcfService.HeaderOutput, ByVal BodyOut() As Domain.TROL)
            MyBase.New
            Me.HeadOut = HeadOut
            Me.BodyOut = BodyOut
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageInputOf_TFNC", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageInputOf_TFNC
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadIn As WcfService.HeaderInput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyIn As Domain.TFNC
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TFNC)
            MyBase.New
            Me.HeadIn = HeadIn
            Me.BodyIn = BodyIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageOutputOf_ListOf_TFNC", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageOutputOf_ListOf_TFNC
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadOut As WcfService.HeaderOutput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyOut() As Domain.TFNC
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadOut As WcfService.HeaderOutput, ByVal BodyOut() As Domain.TFNC)
            MyBase.New
            Me.HeadOut = HeadOut
            Me.BodyOut = BodyOut
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageInputOf_TROLFNC", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageInputOf_TROLFNC
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadIn As WcfService.HeaderInput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyIn As Domain.TROLFNC
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TROLFNC)
            MyBase.New
            Me.HeadIn = HeadIn
            Me.BodyIn = BodyIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageOutputOf_TROLFNC", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageOutputOf_TROLFNC
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadOut As WcfService.HeaderOutput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyOut As Domain.TROLFNC
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadOut As WcfService.HeaderOutput, ByVal BodyOut As Domain.TROLFNC)
            MyBase.New
            Me.HeadOut = HeadOut
            Me.BodyOut = BodyOut
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageInputOf_ListOf_TUSRROL", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageInputOf_ListOf_TUSRROL
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadIn As WcfService.HeaderInput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyIn() As Domain.TUSRROL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn() As Domain.TUSRROL)
            MyBase.New
            Me.HeadIn = HeadIn
            Me.BodyIn = BodyIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageOutputOf_TUSRROL", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageOutputOf_TUSRROL
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadOut As WcfService.HeaderOutput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyOut As Domain.TUSRROL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadOut As WcfService.HeaderOutput, ByVal BodyOut As Domain.TUSRROL)
            MyBase.New
            Me.HeadOut = HeadOut
            Me.BodyOut = BodyOut
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageOutputOf_ListOf_VMEN", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageOutputOf_ListOf_VMEN
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadOut As WcfService.HeaderOutput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyOut() As Domain.VMEN
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadOut As WcfService.HeaderOutput, ByVal BodyOut() As Domain.VMEN)
            MyBase.New
            Me.HeadOut = HeadOut
            Me.BodyOut = BodyOut
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageInputOf_TSYSPAR", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageInputOf_TSYSPAR
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadIn As WcfService.HeaderInput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyIn As Domain.TSYSPAR
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TSYSPAR)
            MyBase.New
            Me.HeadIn = HeadIn
            Me.BodyIn = BodyIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="MessageOutputOf_TSYSPAR", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class MessageOutputOf_TSYSPAR
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public HeadOut As WcfService.HeaderOutput
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BodyOut As Domain.TSYSPAR
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HeadOut As WcfService.HeaderOutput, ByVal BodyOut As Domain.TSYSPAR)
            MyBase.New
            Me.HeadOut = HeadOut
            Me.BodyOut = BodyOut
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IWcfServiceChannel
        Inherits WcfService.IWcfService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WcfServiceClient
        Inherits System.ServiceModel.ClientBase(Of WcfService.IWcfService)
        Implements WcfService.IWcfService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_GetUserRolesByCompanyAndUsername(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_TUSR Implements WcfService.IWcfService.GetUserRolesByCompanyAndUsername
            Return MyBase.Channel.GetUserRolesByCompanyAndUsername(request)
        End Function
        
        Public Function GetUserRolesByCompanyAndUsername(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TUSR, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut As Domain.TUSR) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TUSR = New WcfService.MessageInputOf_TUSR()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_TUSR = CType(Me,WcfService.IWcfService).GetUserRolesByCompanyAndUsername(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_GetFilteredUsers(ByVal request As WcfService.MessageInputOf_GetFilteredOf_TUSR) As WcfService.MessageOutputOf_IListOf_TUSR Implements WcfService.IWcfService.GetFilteredUsers
            Return MyBase.Channel.GetFilteredUsers(request)
        End Function
        
        Public Function GetFilteredUsers(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As WcfService.GetFilteredOfTUSR, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut() As Domain.TUSR) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_GetFilteredOf_TUSR = New WcfService.MessageInputOf_GetFilteredOf_TUSR()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_IListOf_TUSR = CType(Me,WcfService.IWcfService).GetFilteredUsers(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_GetUserByPrimaryKey(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_TUSR Implements WcfService.IWcfService.GetUserByPrimaryKey
            Return MyBase.Channel.GetUserByPrimaryKey(request)
        End Function
        
        Public Function GetUserByPrimaryKey(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TUSR, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut As Domain.TUSR) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TUSR = New WcfService.MessageInputOf_TUSR()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_TUSR = CType(Me,WcfService.IWcfService).GetUserByPrimaryKey(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_InsertUser(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_TUSR Implements WcfService.IWcfService.InsertUser
            Return MyBase.Channel.InsertUser(request)
        End Function
        
        Public Function InsertUser(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TUSR, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut As Domain.TUSR) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TUSR = New WcfService.MessageInputOf_TUSR()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_TUSR = CType(Me,WcfService.IWcfService).InsertUser(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_DeleteUser(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_TUSR Implements WcfService.IWcfService.DeleteUser
            Return MyBase.Channel.DeleteUser(request)
        End Function
        
        Public Function DeleteUser(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TUSR, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut As Domain.TUSR) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TUSR = New WcfService.MessageInputOf_TUSR()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_TUSR = CType(Me,WcfService.IWcfService).DeleteUser(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_UpdateUser(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_TUSR Implements WcfService.IWcfService.UpdateUser
            Return MyBase.Channel.UpdateUser(request)
        End Function
        
        Public Function UpdateUser(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TUSR, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut As Domain.TUSR) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TUSR = New WcfService.MessageInputOf_TUSR()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_TUSR = CType(Me,WcfService.IWcfService).UpdateUser(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_GetFilteredRoles(ByVal request As WcfService.MessageInputOf_GetFilteredOf_TROL) As WcfService.MessageOutputOf_IListOf_TROL Implements WcfService.IWcfService.GetFilteredRoles
            Return MyBase.Channel.GetFilteredRoles(request)
        End Function
        
        Public Function GetFilteredRoles(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As WcfService.GetFilteredOfTROL, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut() As Domain.TROL) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_GetFilteredOf_TROL = New WcfService.MessageInputOf_GetFilteredOf_TROL()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_IListOf_TROL = CType(Me,WcfService.IWcfService).GetFilteredRoles(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_GetRoleByPrimaryKey(ByVal request As WcfService.MessageInputOf_TROL) As WcfService.MessageOutputOf_TROL Implements WcfService.IWcfService.GetRoleByPrimaryKey
            Return MyBase.Channel.GetRoleByPrimaryKey(request)
        End Function
        
        Public Function GetRoleByPrimaryKey(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TROL, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut As Domain.TROL) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TROL = New WcfService.MessageInputOf_TROL()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_TROL = CType(Me,WcfService.IWcfService).GetRoleByPrimaryKey(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_GetAllRoles(ByVal request As WcfService.MessageInputOf_TROL) As WcfService.MessageOutputOf_IListOf_TROL Implements WcfService.IWcfService.GetAllRoles
            Return MyBase.Channel.GetAllRoles(request)
        End Function
        
        Public Function GetAllRoles(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TROL, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut() As Domain.TROL) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TROL = New WcfService.MessageInputOf_TROL()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_IListOf_TROL = CType(Me,WcfService.IWcfService).GetAllRoles(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_GetRolesAndAllowedFunctions(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_ListOf_TROL Implements WcfService.IWcfService.GetRolesAndAllowedFunctions
            Return MyBase.Channel.GetRolesAndAllowedFunctions(request)
        End Function
        
        Public Function GetRolesAndAllowedFunctions(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TUSR, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut() As Domain.TROL) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TUSR = New WcfService.MessageInputOf_TUSR()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_ListOf_TROL = CType(Me,WcfService.IWcfService).GetRolesAndAllowedFunctions(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_GetRolesAssociableToUser(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_IListOf_TROL Implements WcfService.IWcfService.GetRolesAssociableToUser
            Return MyBase.Channel.GetRolesAssociableToUser(request)
        End Function
        
        Public Function GetRolesAssociableToUser(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TUSR, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut() As Domain.TROL) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TUSR = New WcfService.MessageInputOf_TUSR()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_IListOf_TROL = CType(Me,WcfService.IWcfService).GetRolesAssociableToUser(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_GetRolesAssociatedToUser(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_ListOf_TROL Implements WcfService.IWcfService.GetRolesAssociatedToUser
            Return MyBase.Channel.GetRolesAssociatedToUser(request)
        End Function
        
        Public Function GetRolesAssociatedToUser(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TUSR, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut() As Domain.TROL) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TUSR = New WcfService.MessageInputOf_TUSR()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_ListOf_TROL = CType(Me,WcfService.IWcfService).GetRolesAssociatedToUser(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_UpdateRole(ByVal request As WcfService.MessageInputOf_TROL) As WcfService.MessageOutputOf_TROL Implements WcfService.IWcfService.UpdateRole
            Return MyBase.Channel.UpdateRole(request)
        End Function
        
        Public Function UpdateRole(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TROL, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut As Domain.TROL) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TROL = New WcfService.MessageInputOf_TROL()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_TROL = CType(Me,WcfService.IWcfService).UpdateRole(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_InsertRole(ByVal request As WcfService.MessageInputOf_TROL) As WcfService.MessageOutputOf_TROL Implements WcfService.IWcfService.InsertRole
            Return MyBase.Channel.InsertRole(request)
        End Function
        
        Public Function InsertRole(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TROL, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut As Domain.TROL) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TROL = New WcfService.MessageInputOf_TROL()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_TROL = CType(Me,WcfService.IWcfService).InsertRole(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_DeleteRole(ByVal request As WcfService.MessageInputOf_TROL) As WcfService.MessageOutputOf_TROL Implements WcfService.IWcfService.DeleteRole
            Return MyBase.Channel.DeleteRole(request)
        End Function
        
        Public Function DeleteRole(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TROL, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut As Domain.TROL) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TROL = New WcfService.MessageInputOf_TROL()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_TROL = CType(Me,WcfService.IWcfService).DeleteRole(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_getRolesByControllerAction(ByVal request As WcfService.MessageInputOf_TFNC) As WcfService.MessageOutputOf_ListOf_TROL Implements WcfService.IWcfService.getRolesByControllerAction
            Return MyBase.Channel.getRolesByControllerAction(request)
        End Function
        
        Public Function getRolesByControllerAction(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TFNC, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut() As Domain.TROL) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TFNC = New WcfService.MessageInputOf_TFNC()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_ListOf_TROL = CType(Me,WcfService.IWcfService).getRolesByControllerAction(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_GetFuncionsWithPermissions(ByVal request As WcfService.MessageInputOf_TROL) As WcfService.MessageOutputOf_ListOf_TFNC Implements WcfService.IWcfService.GetFuncionsWithPermissions
            Return MyBase.Channel.GetFuncionsWithPermissions(request)
        End Function
        
        Public Function GetFuncionsWithPermissions(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TROL, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut() As Domain.TFNC) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TROL = New WcfService.MessageInputOf_TROL()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_ListOf_TFNC = CType(Me,WcfService.IWcfService).GetFuncionsWithPermissions(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_InsertDeleteAssociationFunctToRole(ByVal request As WcfService.MessageInputOf_TROLFNC) As WcfService.MessageOutputOf_TROLFNC Implements WcfService.IWcfService.InsertDeleteAssociationFunctToRole
            Return MyBase.Channel.InsertDeleteAssociationFunctToRole(request)
        End Function
        
        Public Function InsertDeleteAssociationFunctToRole(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TROLFNC, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut As Domain.TROLFNC) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TROLFNC = New WcfService.MessageInputOf_TROLFNC()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_TROLFNC = CType(Me,WcfService.IWcfService).InsertDeleteAssociationFunctToRole(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_InsertUserRole(ByVal request As WcfService.MessageInputOf_ListOf_TUSRROL) As WcfService.MessageOutputOf_TUSRROL Implements WcfService.IWcfService.InsertUserRole
            Return MyBase.Channel.InsertUserRole(request)
        End Function
        
        Public Function InsertUserRole(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn() As Domain.TUSRROL, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut As Domain.TUSRROL) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_ListOf_TUSRROL = New WcfService.MessageInputOf_ListOf_TUSRROL()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_TUSRROL = CType(Me,WcfService.IWcfService).InsertUserRole(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_DeleteUserRole(ByVal request As WcfService.MessageInputOf_ListOf_TUSRROL) As WcfService.MessageOutputOf_TUSRROL Implements WcfService.IWcfService.DeleteUserRole
            Return MyBase.Channel.DeleteUserRole(request)
        End Function
        
        Public Function DeleteUserRole(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn() As Domain.TUSRROL, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut As Domain.TUSRROL) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_ListOf_TUSRROL = New WcfService.MessageInputOf_ListOf_TUSRROL()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_TUSRROL = CType(Me,WcfService.IWcfService).DeleteUserRole(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_GetMenuByUser(ByVal request As WcfService.MessageInputOf_TUSR) As WcfService.MessageOutputOf_ListOf_VMEN Implements WcfService.IWcfService.GetMenuByUser
            Return MyBase.Channel.GetMenuByUser(request)
        End Function
        
        Public Function GetMenuByUser(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TUSR, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut() As Domain.VMEN) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TUSR = New WcfService.MessageInputOf_TUSR()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_ListOf_VMEN = CType(Me,WcfService.IWcfService).GetMenuByUser(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
        
        Public Function CheckDbConnection() As Boolean Implements WcfService.IWcfService.CheckDbConnection
            Return MyBase.Channel.CheckDbConnection
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_IWcfService_GetSysParByPrimaryKey(ByVal request As WcfService.MessageInputOf_TSYSPAR) As WcfService.MessageOutputOf_TSYSPAR Implements WcfService.IWcfService.GetSysParByPrimaryKey
            Return MyBase.Channel.GetSysParByPrimaryKey(request)
        End Function
        
        Public Function GetSysParByPrimaryKey(ByVal HeadIn As WcfService.HeaderInput, ByVal BodyIn As Domain.TSYSPAR, <System.Runtime.InteropServices.OutAttribute()> ByRef BodyOut As Domain.TSYSPAR) As WcfService.HeaderOutput
            Dim inValue As WcfService.MessageInputOf_TSYSPAR = New WcfService.MessageInputOf_TSYSPAR()
            inValue.HeadIn = HeadIn
            inValue.BodyIn = BodyIn
            Dim retVal As WcfService.MessageOutputOf_TSYSPAR = CType(Me,WcfService.IWcfService).GetSysParByPrimaryKey(inValue)
            BodyOut = retVal.BodyOut
            Return retVal.HeadOut
        End Function
    End Class
End Namespace
